[versions]
agp = "8.13.2"
androidxJunit = "1.1.5"
markwonCore = "4.6.2"
espressoCoreVersion = "3.5.1"
junit = "4.13.2"
appcompat = "1.7.1"
material = "1.12.0"
moshi = "1.15.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.9.2"
lifecycleViewmodelKtx = "2.9.2"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
navigationFragmentVersion = "2.9.3"
navigationUiVersion = "2.9.3"
processPhoenix = "3.0.0"
room = "2.7.2"
roomRuntimeAndroid = "2.7.2"
preference = "1.2.1"

[libraries]
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwonCore" }
markwon-ext-strikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwonCore" }
markwon-ext-tables = { module = "io.noties.markwon:ext-tables", version.ref = "markwonCore" }
moshi-moshi = {module = "com.squareup.moshi:moshi", version.ref = "moshi"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragmentVersion" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUiVersion" }
process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
room = { id = "androidx.room", version.ref = "room" }

